language: python

python:
  - pypy
  - pypy3
  - 2.6
  - 2.7
  - 2.7_with_system_site_packages
  - 3.2
  - 3.3
  - 3.4

install:
  - python setup.py install

script:
  # Simple tests: just run some example commands with options
  - vanity -h
  - vanity --help
  - vanity vanity pillow
  - vanity vanity pillow -q
  - vanity --quiet vanity pillow

after_success:
  - travis_retry pip install pep8 pyflakes
  - pep8 --statistics --count *.py
  - pyflakes *.py | tee >(wc -l)

matrix:
  fast_finish: true
